---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

## Loading the required packages
```{r}
require(tidyverse)
require(tidymodels)
require(parsnip)
require(ranger)
require(usemodels)
require(doParallel)
```


## Importing the data from kaggle as train and test dataset
```{r}
rest_rev=read.csv('/Users/shreshthrathod/Downloads/restaurant-revenue-prediction-2/train.csv')
rest_revTest = read.csv('/Users/shreshthrathod/Downloads/test.csv')
```


# Analyzing the data
```{r}
# Training data
sumType = rest_rev %>% group_by(Type) %>% summarise(summation = n())
ggplot(sumType, aes(x = Type, y = summation)) + geom_bar(stat="identity")


# Test data
sumType = rest_revTest %>% group_by(Type) %>% summarise(summation = n())
ggplot(sumType, aes(x = Type, y = summation)) + geom_bar(stat="identity")

rm(sumType)

# For training data there are only three categories but in the testing data there are four categories ('MB' is the extra categorical variable) which should not be the case as the predictors can't predict on a new unknown category. Hence, we should impute it to 'DT' as 'MB' is more related to drive thru than 'FC' or 'IL'.









# Training data
sum_CityGroup = rest_rev %>% group_by(City.Group) %>% summarise(summation = n())
ggplot(sum_CityGroup, aes(x = City.Group, y = summation)) + geom_bar(stat="identity")


# Test data
sum_CityGroup = rest_revTest %>% group_by(City.Group) %>% summarise(summation = n())
ggplot(sum_CityGroup, aes(x = City.Group, y = summation)) + geom_bar(stat="identity")

rm(sum_CityGroup)

# There's not much of a difference in the training and test set so no changes are required for this column









# Training data
sum_City = rest_rev %>% group_by(City) %>% summarise(summation = n())
ggplot(sum_City, aes(x = City, y = summation)) + geom_bar(stat="identity")
# sum_City %>% View()

# Test data
sum_City = rest_revTest %>% group_by(City) %>% summarise(summation = n())
ggplot(sum_City, aes(x = City, y = summation)) + geom_bar(stat="identity")
# sum_City %>% View()
rm(sum_City)

# In training data set, number of cities are less than the testing set and it won't do any good if we predict on new cities so it is better to drop the city column as we have the geo-location information in the P variables.









ggplot(rest_rev, aes(x= revenue)) + geom_boxplot()

# There are outliers which can affect the overall results during the model building
```


## Preprocessing the training(and validation) and testing data
```{r}
# Removing the outliers in order to get unbiased and better results 

rest_rev = rest_rev %>% filter(revenue < 10000000)


# rest_rev$revenue <- log(1 + rest_rev$revenue)





# Removing the city column from both the datasets as mentioned above

# For training(and validation) data
rest_rev = rest_rev %>% select(-City)

# For testing data
rest_revTest = rest_revTest %>% select(-City)









# Whether it is a 'DT' or 'MB' type restaurant, it can be assumed as an Inline restaurant as they all are one and the same and imputing them to a majority category would a good option for better understanding as well as would have a proportionate data distribution

# For training(and validation) data
rest_rev$Type[rest_rev$Type == 'DT'] = 'IL'

# For testing data
rest_revTest$Type[rest_revTest$Type == 'DT' | rest_revTest$Type == 'MB'] = 'IL'









# Here we have tried to find the number of days the restaurant has been open. For reference, we took a sample data for comparison and also downscale the final values to the factor of 1000 else it would have generated a biased model

# For training(and validation) data
rest_rev$Open.Date = as.Date(rest_rev$Open.Date, format = "%m/%d/%Y") 
max(rest_rev$Open.Date)
rest_rev$days_SinceOpened <- as.numeric(as.Date("2014-02-12")-rest_rev$Open.Date)/1000
# rest_rev$months_SinceOpened <- as.numeric(as.Date("2014-02-12")-rest_rev$Open.Date)/3000
# rest_rev$years_SinceOpened <- as.numeric(as.Date("2014-02-12")-rest_rev$Open.Date)/3650

# For testing data
rest_revTest$Open.Date = as.Date(rest_revTest$Open.Date, format = "%m/%d/%Y") 
max(rest_revTest$Open.Date)
rest_revTest$days_SinceOpened <- as.numeric(as.Date("2014-02-12")-rest_revTest$Open.Date)/1000
# rest_revTest$months_SinceOpened <- as.numeric(as.Date("2014-02-12")-rest_revTest$Open.Date)/3000
# rest_revTest$years_SinceOpened <- as.numeric(as.Date("2014-02-12")-rest_revTest$Open.Date)/3650









# Splitting the date into year, month and day and dropping the Open.Date column from both the datasets

# For training(and validation) data
# rest_rev = rest_rev %>% mutate(year = as.numeric(format(Open.Date, format = "%Y")),
#                                month = as.numeric(format(Open.Date, format = "%m")),
#                                day = as.numeric(format(Open.Date, format = "%d")))

rest_rev = rest_rev %>% select(-Open.Date)

# For testing data
# rest_revTest = rest_revTest %>% mutate(year = as.numeric(format(Open.Date, format = "%Y")),
#                              month = as.numeric(format(Open.Date, format = "%m")),
#                              day = as.numeric(format(Open.Date, format = "%d")))

rest_revTest = rest_revTest %>% select(-Open.Date)









# For training(and validation) data
rest_rev = rest_rev %>% select(-Id) # This column has no significance in the dataset
rest_rev$City.Group = as.factor(rest_rev$City.Group) # Convert the columns to factors
rest_rev$Type = as.factor(rest_rev$Type) # Convert the columns to factors

# For testing data
ID = rest_revTest %>% select(Id)
rest_revTest = rest_revTest %>% select(-Id) # This column has no significance in the dataset
rest_revTest$City.Group = as.factor(rest_revTest$City.Group) # Convert the columns to factors
rest_revTest$Type = as.factor(rest_revTest$Type) # Convert the columns to factors

```

```{r}
set.seed(271)
rest_rev_split<-initial_split(rest_rev, prop=.7, strata = revenue)
rest_rev_split_training<-rest_rev_split%>% training()
rest_rev_split_test<-rest_rev_split%>% testing()
```


```{r}
rest_rev_split_recipe<- recipe(revenue ~ ., data= rest_rev_split_training)%>%
                    step_rm(City.Group, Type) %>%
                    step_dummy(all_nominal(), -all_outcomes()) ## -all_outcomes() is not necessary since we will use regression 
```


```{r}
rest_rev_split_recipe%>%prep()%>%bake(rest_rev_split_training)   ## applies the transformation steps to the daeta (in this case to homes_training)
rest_rev_split_recipe%>%prep()%>%bake(rest_rev_split_test)
```


```{r}
lm_model<-linear_reg() %>% set_engine('lm')

svm_model<-svm_poly() %>% 
            set_engine("kernlab") %>% 
            set_mode("regression") %>% 
            translate()
nnmodel = mlp(hidden_units = 200, dropout = 0.1, epochs = 500, activation = 'linear') %>% 
          set_engine("keras") %>% 
          set_mode("regression") %>% 
          translate()

rest_rev_workflow<-workflow()%>%
                add_model(svm_model)%>%
                add_recipe(rest_rev_split_recipe)
```


## Model Fitting
```{r}
model_fit<-rest_rev_workflow%>%fit(rest_rev_split_training)

View(tidy(model_fit))
```


## Training data accuracy 
```{r}
training_result=predict(model_fit, rest_rev_split_training)%>%bind_cols(rest_rev_split_training%>%select(revenue))

metrics(training_result, truth=revenue, estimate=.pred)
```

## Testing data accuracy
```{r}
testing_results=predict(model_fit, rest_rev_split_test)%>%bind_cols(rest_rev_split_test%>%select(revenue))

metrics(testing_results, truth=revenue, estimate=.pred)

# testing_results=predict(model_fit, rest_rev_split_test)
```


```{r}

```




























































































```{r}
Avg_revenue=rest_rev%>%group_by(City)%>%summarise(avg_rev=mean(revenue))
Avg_revenue
ggplot(data=Avg_revenue, aes(x=City, y=as.numeric(avg_rev))) +
  geom_bar(stat="identity", fill="black")
```


```{r}
Avg_revenue=rest_rev%>%group_by(Type)%>%summarise(avg_rev=mean(revenue))
Avg_revenue
ggplot(data=Avg_revenue, aes(x=Type, y=as.numeric(avg_rev))) +
  geom_bar(stat="identity", fill="black")


```


```{r}
Avg_revenue=rest_rev%>%group_by(P1)%>%summarise(avg_rev=mean(revenue))
FORP1<-ggplot(data=Avg_revenue, aes(x=avg_rev, y=P1, group=1,palette = "jco")) +
  geom_line()+
  geom_point()

Avg_revenue=rest_rev%>%group_by(P2)%>%summarise(avg_rev=mean(revenue))
FORP2<-ggplot(data=Avg_revenue, aes(x=avg_rev, y=P2, group=1,palette = "jco")) +
  geom_line()+
  geom_point()

Avg_revenue=rest_rev%>%group_by(P3)%>%summarise(avg_rev=mean(revenue))
FORP3<-ggplot(data=Avg_revenue, aes(x=avg_rev, y=P3, group=1,palette = "jco")) +
  geom_line()+
  geom_point()

Avg_revenue=rest_rev%>%group_by(P4)%>%summarise(avg_rev=mean(revenue))
FORP4<-ggplot(data=Avg_revenue, aes(x=avg_rev, y=P4, group=1,palette = "jco")) +
  geom_line()+
  geom_point()

Avg_revenue=rest_rev%>%group_by(P5)%>%summarise(avg_rev=mean(revenue))
FORP5<-ggplot(data=Avg_revenue, aes(x=avg_rev, y=P5, group=1,palette = "jco")) +
  geom_line()+
  geom_point()

Avg_revenue=rest_rev%>%group_by(P6)%>%summarise(avg_rev=mean(revenue))
FORP6<-ggplot(data=Avg_revenue, aes(x=avg_rev, y=P6, group=1,palette = "jco")) +
  geom_line()+
  geom_point()

Avg_revenue=rest_rev%>%group_by(P7)%>%summarise(avg_rev=mean(revenue))
FORP7<-ggplot(data=Avg_revenue, aes(x=avg_rev, y=P7, group=1,palette = "jco")) +
  geom_line()+
  geom_point()

Avg_revenue=rest_rev%>%group_by(P8)%>%summarise(avg_rev=mean(revenue))
FORP8<-ggplot(data=Avg_revenue, aes(x=avg_rev, y=P8, group=1,palette = "jco")) +
  geom_line()+
  geom_point()

Avg_revenue=rest_rev%>%group_by(P9)%>%summarise(avg_rev=mean(revenue))
FORP9<-ggplot(data=Avg_revenue, aes(x=avg_rev, y=P9, group=1,palette = "jco")) +
  geom_line()+
  geom_point()



require(gridExtra)
grid.arrange(FORP1,FORP2,FORP3,FORP4,FORP5,FORP6,FORP7,FORP8,FORP9,ncol=3,nrow=3)
```


```{r}
longer_data <- rest_rev %>%
  pivot_longer(P1:P37, names_to = "Predictions", values_to = "response")
print(longer_data)
```


```{r}
summary(rest_rev)
attach(rest_rev)
#x<-cbind(City,City.Group,Type,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16,P17,P18,P19,P20,P21,P22,P23,P24,P25,P26,P27,P28,P29,P30,P31,P32,P33,P34,P35,P36,P37)

x<-cbind(P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16,P17,P18,P19,P20,P21,P22,P23,P24,P25,P26,P27,P28,P29,P30,P31,P32,P33,P34,P35,P36,P37)
```


```{r}
cor(x)
```


```{r}
PCA1<-prcomp(x,scores=TRUE,  cor= TRUE)
summary(PCA1)
```


```{r}
PCA1$loadings
```


```{r}
plot(PCA1)
```


```{r}
#screeplot(PCA1,type='line', main='Scree Plot')
```


```{r}
screeplot(PCA1, type = "line", npcs = 15, main = "Screeplot of the first 10 PCs")
abline(h = 1, col="red", lty=5)
legend("topright", legend=c("Eigenvalue > 1"),
       col=c("red"), lty=5, cex=0.5)
```

```{r}
cumpro <- cumsum(PCA1$sdev^2 / sum(PCA1$sdev^2))
plot(cumpro[0:36], xlab = "PC #", ylab = "Amount of explained variance", main = "Cumulative variance plot")
abline(v = 16, col="blue", lty=5)
abline(h = 0.97999, col="blue", lty=5)
legend("bottomright", legend=c("Cut-off @ PC16"),
       col=c("blue"), lty=4, cex=0.4)
```

```{r}
biplot(PCA1)
```


```{r}
PCA1$scores[1:10,]
```

```{r}

```
 

